package org.manage.common.module;

import org.manage.common.module.base.BaseServer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Server extends BaseServer<Server> {
	public static final Server dao = new Server().dao();
}

