package org.manage.common.module;

import org.manage.common.module.base.BaseSystemServer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemServer extends BaseSystemServer<SystemServer> {
	public static final SystemServer dao = new SystemServer().dao();
}

