package org.manage.common.module;

import org.manage.common.module.base.BaseSystem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class System extends BaseSystem<System> {
	public static final System dao = new System().dao();
}

