package org.manage.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAccount<M extends BaseAccount<M>> extends Model<M> implements IBean {

	/**
	 * 主键 主键唯一标识
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 主键唯一标识
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return getDate("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return getDate("updated_time");
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 用户 用户名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 用户 用户名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 账号 账号
	 */
	public void setAccount(java.lang.String account) {
		set("account", account);
	}
	
	/**
	 * 账号 账号
	 */
	public java.lang.String getAccount() {
		return getStr("account");
	}
	
	/**
	 * 密码 密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 密码 密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	/**
	 * 对象 1-系统账号 2-服务器账号
	 */
	public void setObject(java.lang.Integer object) {
		set("object", object);
	}
	
	/**
	 * 对象 1-系统账号 2-服务器账号
	 */
	public java.lang.Integer getObject() {
		return getInt("object");
	}
	
	/**
	 * 对象id 即系统和服务器主键,表示该账号是哪里的登录账号(可以为空,即账号是本系统的登录账号)
	 */
	public void setObjectId(java.math.BigInteger objectId) {
		set("object_id", objectId);
	}
	
	/**
	 * 对象id 即系统和服务器主键,表示该账号是哪里的登录账号(可以为空,即账号是本系统的登录账号)
	 */
	public java.math.BigInteger getObjectId() {
		return get("object_id");
	}
	
}

