package org.manage.common.module.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	/**
	 * 主键 主键唯一标识
	 */
	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	/**
	 * 主键 主键唯一标识
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("created_time", createdTime);
	}
	
	/**
	 * 创建时间 创建时间
	 */
	public java.util.Date getCreatedTime() {
		return getDate("created_time");
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updated_time", updatedTime);
	}
	
	/**
	 * 更新时间 更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return getDate("updated_time");
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
	}
	
	/**
	 * 是否删除 0-未删除 1-已删除
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}
	
	/**
	 * 用户名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 用户名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 账号
	 */
	public void setAccount(java.lang.String account) {
		set("account", account);
	}
	
	/**
	 * 账号
	 */
	public java.lang.String getAccount() {
		return getStr("account");
	}
	
	/**
	 * 密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	/**
	 * 加密盐
	 */
	public void setSalt(java.lang.String salt) {
		set("salt", salt);
	}
	
	/**
	 * 加密盐
	 */
	public java.lang.String getSalt() {
		return getStr("salt");
	}
	
	/**
	 * 用户角色 1-超级管理员 2-普通用户
	 */
	public void setRole(java.lang.Integer role) {
		set("role", role);
	}
	
	/**
	 * 用户角色 1-超级管理员 2-普通用户
	 */
	public java.lang.Integer getRole() {
		return getInt("role");
	}
	
}

